services:
  postgres:
    image: postgres:16-alpine
    container_name: motubas-db
    environment:
      POSTGRES_USER: motubas
      POSTGRES_PASSWORD: motubas123
      POSTGRES_DB: motubas
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
